FROM node:20-alpine

WORKDIR /app

# Dependencias requeridas por Prisma en Alpine
RUN apk add --no-cache libc6-compat openssl

COPY package.json package-lock.json ./
RUN npm install

COPY . .

RUN npx prisma generate

EXPOSE 3009

CMD ["npm", "run", "dev"]